from selenium import webdriver
browser = webdriver.Chrome(executable_path=r"C:\SeleniumDrivers\chromedriver.exe")
browser=webdriver.Chrome()
time.sleep(10)
browser.get("https://codechef.com")
username_element=browser.find_element_by_id("edit-name")
username_element.send_keys("praritvij")
password_element=browser.find_element_by_id("edit-pass")
password_element.send_keys("anil@57822")
browser.find_element_by_id("edit-submit").click()
browser.get("https://www.codechef.com/submit/TEST")
time.sleep(10)
browser.find_element_by_id("edit_area_toggle_checkbox_edit-program").click()
with open("solution.cpp.txt",'r') as f:
    code=f.read()
code_element=browser.find_element_by_id('edit-program')
code_element.send_keys(code)
browser.find_element_by_xpath('//*[@id="edit-language"]/option[2]')
browser.find_element_by_id("edit-submit").click()
